#!/bin/sh
# Assembles perspective.asm and writes the bytes the patcher carries,
# src/uwpatch_perspective.h. Needs nasm and python3; the header is
# checked in, so building uwpatch does not.
set -e
here=$(cd "$(dirname "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
nasm -f bin -o "$tmp/perspective.bin" "$here/perspective.asm"
python3 - "$tmp/perspective.bin" "$here/../src/uwpatch_perspective.h" <<'PY'
import sys
b = open(sys.argv[1], 'rb').read()
assert len(b) == 0x898 - 0x60, hex(len(b))
rows = [', '.join('0x%02x' % c for c in b[i:i + 12]) for i in range(0, len(b), 12)]
with open(sys.argv[2], 'w', newline='\n') as f:
    f.write('/* SPDX-License-Identifier: MIT */\n'
            '/* Generated by patch/build.sh from perspective.asm: the\n'
            ' * graphics segment from 0x60 to 0x897 as the patch would have it. The\n'
            ' * patcher writes only 0x60..0x362 and 0x422..0x897, and not the relocated\n'
            ' * words at 0x1dd and 0x553, for which these bytes hold places. */\n'
            '#ifndef UWPATCH_PERSPECTIVE_H\n#define UWPATCH_PERSPECTIVE_H\n\n'
            '#define UWPATCH_PERSPECTIVE_ORG 0x60\n\n'
            'static const unsigned char uwpatch_perspective[%d] = {\n    ' % len(b))
    f.write(',\n    '.join(rows))
    f.write('\n};\n\n#endif\n')
print('wrote', sys.argv[2], len(b), 'bytes')
PY
